### ISSUE TITLE
CheckList: 151208

### ISSUE THREAD

**Issue by Manjiz** [o2team/UFT#1]
## 阶段优化（2015年12月08日）

**登录**

1. [x] 登录后特定页跳转

**广场**

1. [x] 游客用户和非管理员用户不能看到未审核需求
2. [x] 拖动排期功能
3. [x] ✘ 一键邮送排期表功能
4. [x] ✘ 排期表显示/隐藏交互
5. [ ] 节假日
6. [x] 拆分广场 = 广场 + 排期

**详情**

1. [x] 头部 UI 优化
2. [ ] 附件携带信息
3. [x] 需求类型排第一位

**个人信息**

1. [x] ✘ 头像系统
2. [x] 响应式页面

**其他**

1. [ ] 消息中心
2. [x] 响应式头部导航
3. [x] “我的”和“待审”响应式页面
